//all file install using npm init will be installed in package.json folder....
// just type npm init in comand terminal and set all the value as u want ...and keep default....
//all library will be under package.json
//package.json-lock give extra information about dependecies
// const chalk = require("chalk")
// console.log(chalk.blue('this will return text in blue colour!'));
//u can use many chalk like.....italic, bold, underline etc.... 